abbrevs:
  # Git
  - name: git
    abbr: g
    snippet: git
  - name: git branch
    abbr: b
    snippet: branch
    context: '^git\s'
    global: true
  - name: git branch -D
    abbr: bd
    snippet: branch -D
    context: '^git\s'
    global: true
  - name: git checkout
    abbr: ch
    snippet: checkout
    context: '^git\s'
    global: true
  - name: git commit
    abbr: c
    snippet: commit
    context: '^git\s'
    global: true
  - name: git commit -m
    abbr: cm
    snippet: commit -m '{}'
    context: '^git\s'
    global: true
  - name: git commit --amend '-S'
    abbr: ca
    snippet: commit --amend '-S'
    context: '^git\s'
    global: true
  - name: Fetch current branch name
    abbr: B
    snippet: $(git symbolic-ref --short HEAD)
    evaluate: true
    context: '^git\s'
    global: true
  - name: git pull
    abbr: pl
    snippet: pull
    context: '^git\s'
    global: true
  - name: git push
    abbr: ph
    snippet: push
    context: '^git\s'
    global: true
  - name: git push origin
    abbr: pho
    snippet: push origin
    context: '^git\s'
    global: true
  - name: git push --force-with-lease --force-if-includes
    abbr: gpf
    snippet: git push --force-with-lease --force-if-includes
    global: true

  # Docker
  - name: docker
    abbr: d
    snippet: docker
  - name: docker ps
    abbr: dps
    snippet: docker ps
    global: true
  - name: docker exec -it
    abbr: deit
    snippet: docker exec -it
    global: true
  - name: docker logs
    abbr: dlogs
    snippet: docker logs
    global: true
  - name: docker images
    abbr: dimgs
    snippet: docker images
    global: true
  - name: docker rmi `dimgs -aq`
    abbr: drminone
    snippet: docker rmi `dimgs -aq`
    global: true

  # Docker compose
  - name: docker compose
    abbr: dc
    snippet: docker compose
    global: true
  - name: docker compose up
    abbr: dcup
    snippet: docker compose up
    global: true
  - name: docker compose up -d
    abbr: dcupd
    snippet: docker compose up -d
    global: true
  - name: docker compose down
    abbr: dcdown
    snippet: docker compose down
    global: true

  # Docker
  - name: pnpm
    abbr: pn
    snippet: pnpm
  - name: pnpm install
    abbr: i
    snippet: install
    context: '^pnpm\s'
    global: true
  - name: pnpm add
    abbr: a
    snippet: add
    context: '^pnpm\s'
    global: true
  - name: pnpm add -D
    abbr: ad
    snippet: add -D
    context: '^pnpm\s'
    global: true
  - name: pnpm remove
    abbr: rm
    snippet: remove
    context: '^pnpm\s'
    global: true
  - name: pnpm run
    abbr: r
    snippet: run
    context: '^pnpm\s'
    global: true
  - name: pnpm dlx
    abbr: d
    snippet: dlx
    context: '^pnpm\s'
    global: true
  - name: pnpm exec
    abbr: e
    snippet: exec
    context: '^pnpm\s'
    global: true

  # Bun
  - name: bun
    abbr: bn
    snippet: bun
  - name: bun install
    abbr: i
    snippet: install
    context: '^bun\s'
    global: true
  - name: bun add
    abbr: a
    snippet: add
    context: '^bun\s'
    global: true
  - name: bun install
    abbr: ad
    snippet: add -D
    context: '^bun\s'
    global: true
  - name: bun remove
    abbr: rm
    snippet: remove
    context: '^bun\s'
    global: true
  - name: bun run
    abbr: r
    snippet: run
    context: '^bun\s'
    global: true
  - name: bunx
    abbr: bnx
    snippet: bunx
